services:
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: db123
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    volumes:
      - ./postgreSQL:/var/lib/postgresql/data
    ports:
      - 5436:5432